# LSTM --输入输出

In [1]:
import numpy
import torch
import torch.nn as nn

In [3]:
lstm = nn.LSTM(input_size=1,hidden_size=10,num_layers=1,batch_first=True)
            #    输入维度        隐藏层维度      隐藏层个数

In [6]:
x = torch.randn(3,8,1) # [batch_size,squ_len,input_size]

In [8]:
print(x)
print(x.shape)

tensor([[[-1.3441],
         [ 0.2597],
         [ 0.7641],
         [-1.0819],
         [ 0.4998],
         [-0.6581],
         [-0.1684],
         [ 1.6441]],

        [[ 0.9782],
         [ 0.5258],
         [-0.4318],
         [-1.6443],
         [-1.2275],
         [-0.3105],
         [-0.4515],
         [ 1.3805]],

        [[ 0.5063],
         [-0.0070],
         [-0.1929],
         [-0.7370],
         [ 0.4722],
         [ 2.4418],
         [-0.2218],
         [ 0.5792]]])
torch.Size([3, 8, 1])


In [9]:
h0 = torch.randn(1,3,10)  # [num_layer,batch_size,hidden_size]
c0 = torch.randn(1,3,10)  # [num_layer,batch_size,hidden_size]

In [12]:
print(h0)
print(c0)

tensor([[[-0.5623, -1.2483, -0.9535, -0.8735,  0.2953,  0.1738,  0.2948,
           1.0053,  0.9218, -1.4825],
         [-0.4303,  1.6830,  0.1912,  0.1210,  0.2317,  3.2839, -2.0354,
           0.4433,  1.8408, -0.4988],
         [-0.4463,  0.0781,  0.9076,  1.6905,  0.1598,  0.5022, -1.3670,
          -0.0733, -0.7455, -0.0047]]])
tensor([[[-0.1380, -1.1539,  1.0524, -0.5310, -0.1972, -2.6896,  2.2847,
          -0.7288, -0.7166,  0.3988],
         [-0.3708, -1.0458, -0.0574,  0.7046,  0.0920,  1.4747, -0.2027,
          -0.0510,  0.5212, -1.1674],
         [ 1.4382, -3.0216,  0.3858,  0.3874, -0.9814,  1.0712, -1.5335,
           0.7044,  0.7809, -1.4067]]])


In [16]:
out,(hn,cn)= lstm(x,(h0,c0))

In [17]:
print(out)

tensor([[[-1.3318e-01, -3.7521e-01,  2.3112e-01,  1.8115e-02, -9.6754e-02,
          -2.4328e-01,  4.0477e-01, -1.1720e-01, -4.6640e-02,  3.5131e-01],
         [-7.7874e-02, -2.8781e-01,  3.3744e-02,  8.6280e-02, -6.5590e-02,
          -3.4324e-01,  3.1229e-01, -1.0264e-01, -4.9602e-02,  1.4761e-01],
         [-1.0051e-01, -9.2136e-02, -7.4865e-02,  3.9223e-02, -5.2585e-02,
          -1.7315e-01,  9.4596e-02, -5.3734e-02, -6.2266e-02,  6.5158e-02],
         [-1.6713e-02, -9.7077e-02, -3.0723e-02,  2.0942e-01,  2.6355e-02,
          -2.9985e-03,  5.7109e-02, -9.4584e-02, -1.0013e-02, -3.8543e-02],
         [-3.9129e-02, -2.0476e-02, -8.8209e-02,  1.1773e-01,  2.3016e-02,
           1.6670e-02, -6.4710e-02, -2.3301e-02, -4.3901e-02, -3.5891e-02],
         [-2.9780e-03, -4.7396e-02, -5.3107e-02,  2.0670e-01,  6.0633e-02,
           6.5290e-02, -5.8523e-02, -3.4662e-02, -2.0630e-02, -7.9154e-02],
         [-1.0611e-03, -3.9120e-02, -6.5953e-02,  1.9023e-01,  6.5775e-02,
           6.7423e-

In [18]:
print(out.shape)

torch.Size([3, 8, 10])


In [19]:
fc1 = nn.Linear(in_features=10,out_features=1)
y = fc1(out)

In [22]:
print(y.shape)

torch.Size([3, 8, 1])


In [25]:
print(y[:,-1,:])  #取每批数据的最后一个作为每批得到的数据

tensor([[-0.1861],
        [-0.2011],
        [-0.1733]], grad_fn=<SliceBackward0>)
